### ISSUE TITLE
8 test cases failure on Node.js 9.8 (and probably above)

### ISSUE THREAD

**Issue by kenny-y** [RobotWebTools/rclnodejs#321]
The error:

```
$ npm test

<many lines of logs>

 579 passing (45s)
  8 failing

  1) Rclnodejs message type data testing
       Char data checking:
     RangeError [ERR_INVALID_OPT_VALUE]: The value "-129" is invalid for option "value"
      at checkInt (buffer.js:1274:11)
      at Buffer.writeInt8 (buffer.js:1441:5)
      at Object.set (node_modules/ref/lib/ref.js:865:18)
      at Object.set (node_modules/ref/lib/ref.js:487:10)
      at StructType.desc.set [as data] (node_modules/ref-struct/lib/struct.js:225:16)
      at CharWrapper.set data [as data] (generated/std_msgs/std_msgs__msg__Char.js:95:26)
      at assertThrowsError (test/test-primitive-msg-type-check.js:60:16)
      at tryBlock (assert.js:159:5)
      at innerThrows (assert.js:178:18)
      at Function.throws (assert.js:205:3)

  2) Rclnodejs message type data testing
       Byte data checking:
     RangeError [ERR_INVALID_OPT_VALUE]: The value "-1" is invalid for option "value"
      at checkInt (buffer.js:1274:11)
      at Buffer.writeUInt8 (buffer.js:1325:7)
      at Object.set (node_modules/ref/lib/ref.js:883:18)
      at Object.set (node_modules/ref/lib/ref.js:487:10)
      at StructType.desc.set [as data] (node_modules/ref-struct/lib/struct.js:225:16)
      at ByteWrapper.set data [as data] (generated/std_msgs/std_msgs__msg__Byte.js:95:26)
      at assertThrowsError (test/test-primitive-msg-type-check.js:77:16)
      at tryBlock (assert.js:159:5)
      at innerThrows (assert.js:178:18)
      at Function.throws (assert.js:205:3)

  3) Rclnodejs message type data testing
       Int8 data checking:
     RangeError [ERR_INVALID_OPT_VALUE]: The value "-129" is invalid for option "value"
      at checkInt (buffer.js:1274:11)
      at Buffer.writeInt8 (buffer.js:1441:5)
      at Object.set (node_modules/ref/lib/ref.js:865:18)
      at Object.set (node_modules/ref/lib/ref.js:487:10)
      at StructType.desc.set [as data] (node_modules/ref-struct/lib/struct.js:225:16)
      at Int8Wrapper.set data [as data] (generated/std_msgs/std_msgs__msg__Int8.js:95:26)
      at assertThrowsError (test/test-primitive-msg-type-check.js:111:16)
      at tryBlock (assert.js:159:5)
      at innerThrows (assert.js:178:18)
      at Function.throws (assert.js:205:3)

  4) Rclnodejs message type data testing
       UInt8 data checking:
     RangeError [ERR_INVALID_OPT_VALUE]: The value "-1" is invalid for option "value"
      at checkInt (buffer.js:1274:11)
      at Buffer.writeUInt8 (buffer.js:1325:7)
      at Object.set (node_modules/ref/lib/ref.js:883:18)
      at Object.set (node_modules/ref/lib/ref.js:487:10)
      at StructType.desc.set [as data] (node_modules/ref-struct/lib/struct.js:225:16)
      at UInt8Wrapper.set data [as data] (generated/std_msgs/std_msgs__msg__UInt8.js:95:26)
      at assertThrowsError (test/test-primitive-msg-type-check.js:128:16)
      at tryBlock (assert.js:159:5)
      at innerThrows (assert.js:178:18)
      at Function.throws (assert.js:205:3)

  5) Rclnodejs message type data testing
       Int16 data checking:
     RangeError [ERR_INVALID_OPT_VALUE]: The value "-32769" is invalid for option "value"
      at checkInt (buffer.js:1274:11)
      at Buffer.writeInt16LE (buffer.js:1451:5)
      at Object.set (node_modules/ref/lib/ref.js:898:52)
      at Object.set (node_modules/ref/lib/ref.js:487:10)
      at StructType.desc.set [as data] (node_modules/ref-struct/lib/struct.js:225:16)
      at Int16Wrapper.set data [as data] (generated/std_msgs/std_msgs__msg__Int16.js:95:26)
      at assertThrowsError (test/test-primitive-msg-type-check.js:145:16)
      at tryBlock (assert.js:159:5)
      at innerThrows (assert.js:178:18)
      at Function.throws (assert.js:205:3)

  6) Rclnodejs message type data testing
       UInt16 data checking:
     RangeError [ERR_INVALID_OPT_VALUE]: The value "-1" is invalid for option "value"
      at checkInt (buffer.js:1274:11)
      at Buffer.writeUInt16LE (buffer.js:1336:7)
      at Object.set (node_modules/ref/lib/ref.js:913:53)
      at Object.set (node_modules/ref/lib/ref.js:487:10)
      at StructType.desc.set [as data] (node_modules/ref-struct/lib/struct.js:225:16)
      at UInt16Wrapper.set data [as data] (generated/std_msgs/std_msgs__msg__UInt16.js:95:26)
      at assertThrowsError (test/test-primitive-msg-type-check.js:162:16)
      at tryBlock (assert.js:159:5)
      at innerThrows (assert.js:178:18)
      at Function.throws (assert.js:205:3)

  7) Rclnodejs message type data testing
       Int32 data checking:
     RangeError [ERR_INVALID_OPT_VALUE]: The value "-2147483649" is invalid for option "value"
      at checkInt (buffer.js:1274:11)
      at Buffer.writeInt32LE (buffer.js:1473:5)
      at Object.set (node_modules/ref/lib/ref.js:928:52)
      at Object.set (node_modules/ref/lib/ref.js:487:10)
      at StructType.desc.set [as data] (node_modules/ref-struct/lib/struct.js:225:16)
      at Int32Wrapper.set data [as data] (generated/std_msgs/std_msgs__msg__Int32.js:95:26)
      at assertThrowsError (test/test-primitive-msg-type-check.js:179:16)
      at tryBlock (assert.js:159:5)
      at innerThrows (assert.js:178:18)
      at Function.throws (assert.js:205:3)

  8) Rclnodejs message type data testing
       UInt32 data checking:
     RangeError [ERR_INVALID_OPT_VALUE]: The value "-1" is invalid for option "value"
      at checkInt (buffer.js:1274:11)
      at Buffer.writeUInt32LE (buffer.js:1360:7)
      at Object.set (node_modules/ref/lib/ref.js:943:53)
      at Object.set (node_modules/ref/lib/ref.js:487:10)
      at StructType.desc.set [as data] (node_modules/ref-struct/lib/struct.js:225:16)
      at UInt32Wrapper.set data [as data] (generated/std_msgs/std_msgs__msg__UInt32.js:95:26)
      at assertThrowsError (test/test-primitive-msg-type-check.js:196:16)
      at tryBlock (assert.js:159:5)
      at innerThrows (assert.js:178:18)
      at Function.throws (assert.js:205:3)

```

I believe the root cause is here (see below code), on newer version of Node.js, it's a `RangeError` instead of `TypeError`, so I believe we should change `assertThrowsError()` function in `utils.js`, make this parameter an array and pass two types as the array argument to adapt the change in Node.js.

```JavaScript
// test/test-primitive-msg-type-check.js
  it('Char data checking', function() {
    var node = rclnodejs.createNode('char');
    var msgChar = rclnodejs.require('std_msgs').msg.Char;
    var msg = new msgChar();

    msg.data = 'A';
    assert.deepStrictEqual(typeof msg.data, 'number');
    assert.deepStrictEqual(msg.data, 65);

    assertThrowsError(() => {
      msg.data = -129;
    }, TypeError, 'out of bounds', 'Char should be in [-128, 127]');
    assertThrowsError(() => {
      msg.data = 128;
    }, TypeError, 'out of bounds', 'Char should be in [-128, 127]');
  });
```

```JavaScript
// utils.js
function assertThrowsError(operation, errorType, errMsg, message) {
  assert.throws(operation, function(err) {
    var containedMsg = new RegExp(errMsg);
    if ((err instanceof errorType) && containedMsg.test(err)) {
      return true;
    }
    return false;
  }, message);
}

```

**Comment by qiuzhong** [comment]
Thanks. I'll try it on higher version of Node.js.

**Comment by qiuzhong** [comment]
With Node.js `9.8`, those test cases failed due to a different error type.
With Node.js `10.x`, there're even more test cases failed: The `std_msgs/msg/Bool` data checking as `assert.ifError()` of Node.js changed.

**Comment by qiuzhong** [comment]
Fixed and verified on `Node.js 8.11.1/9.8.0/10.1.0`.
