### ISSUE TITLE
Build error when npm install

### ISSUE THREAD

**Issue by shinhwap** [RobotWebTools/rclnodejs#485]
My ros2 is built from source, https://index.ros.org/doc/ros2/Installation/Linux-Install-Debians/
I use the step in README, when I run npm install:

make: Entering directory '/home/a50044/Desktop/ROS/rclnodejs/build'
  CXX(target) Release/obj.target/rclnodejs/src/addon.o
  CXX(target) Release/obj.target/rclnodejs/src/executor.o
In file included from ../src/executor.cpp:15:0:
../src/executor.hpp: In constructor ‘rclnodejs::Executor::Executor(rclnodejs::HandleManager*, rclnodejs::Executor::Delegate*)’:
../src/executor.hpp:52:18: warning: ‘rclnodejs::Executor::context_’ will be initialized after [-Wreorder]
   rcl_context_t* context_;
                  ^~~~~~~~
../src/executor.hpp:51:13: warning:   ‘rclnodejs::Executor::Delegate* rclnodejs::Executor::delegate_’ [-Wreorder]
   Delegate* delegate_;
             ^~~~~~~~~
../src/executor.cpp:29:1: warning:   when initialized here [-Wreorder]
 Executor::Executor(HandleManager* handle_manager, Delegate* delegate)
 ^~~~~~~~
../src/executor.cpp: In static member function ‘static void rclnodejs::Executor::Run(void*)’:
../src/executor.cpp:100 :19: error: could not convert ‘executor->rclnodejs::Executor::context_’ from ‘rcl_context_t*’ to ‘rcl_allocator_t {aka rcutils_allocator_t}’
         executor->context_, rcl_get_default_allocator());
         ~~~~~~~~~~^~~~~~~~
rclnodejs.target.mk:124: recipe for target 'Release/obj.target/rclnodejs/src/executor.o' failed
make: *** [Release/obj.target/rclnodejs/src/executor.o] Error 1
make: Leaving directory '/home/a50044/Desktop/ROS/rclnodejs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/a50044/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-47-generic
gyp ERR! command "/home/a50044/.nvm/versions/node/v10.15.3/bin/node" "/home/a50044/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/a50044/Desktop/ROS/rclnodejs
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rclnodejs@0.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rclnodejs@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by shinhwap** [comment]
I can use npm i rclnodejs@<version>
So close this issue
