### ISSUE TITLE
Error Installing via npm or Github link

### ISSUE THREAD

**Issue by caelinsutch** [RobotWebTools/rclnodejs#672]
On Ubuntu 20.04 with the Foxy release, I get the follow errors when trying to install rclnodejs. This happens when I put `    "rclnodejs":"RobotWebTools/rclnodejs#foxy-fitzroy"` in my package.json or if I install via `npm i rclnodejs`

```
error /home/caelin/Github/AwesomeProject/node_modules/rclnodejs: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/caelin/Github/AwesomeProject/node_modules/rclnodejs
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@7.0.0
gyp info using node@12.18.2 | linux | x64
gyp info find Python using Python version 3.8.2 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/caelin/.config/yarn/global/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/caelin/Github/AwesomeProject/node_modules/rclnodejs/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/caelin/.config/yarn/global/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/caelin/.cache/node-gyp/12.18.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/caelin/.cache/node-gyp/12.18.2',
gyp info spawn args   '-Dnode_gyp_dir=/home/caelin/.config/yarn/global/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/caelin/.cache/node-gyp/12.18.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/caelin/Github/AwesomeProject/node_modules/rclnodejs',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
[eval]:1
console.log(process.env.AMENT_PREFIX_PATH.replace(/:/g, '/include/ ') + '/include/')
                                          ^

TypeError: Cannot read property 'replace' of undefined
    at [eval]:1:43
    at Script.runInThisContext (vm.js:120:20)
    at Object.runInThisContext (vm.js:311:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at evalScript (internal/process/execution.js:94:25)
    at internal/main/eval_string.js:23:3
gyp: Call to 'node -e "console.log(process.env.AMENT_PREFIX_PATH.replace(/:/g, '/include/ ') + '/include/')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/caelin/.config/yarn/global/node_modules/node-gyp/lib/configure.js:350:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-40-generic
gyp ERR! command "/home/caelin/.nvm/versions/node/v12.18.2/bin/node" "/home/caelin/.yarn/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/caelin/Github/AwesomeProject/node_modules/rclnodejs

```

**Comment by minggangw** [comment]
Did you [source](https://index.ros.org/doc/ros2/Installation/Foxy/Linux-Install-Binary/#sourcing-the-setup-script) the install script? It seems that AMENT_PREFIX_PATH is undefined from the log.

```bash
. ~/ros2_foxy/ros2-linux/setup.bash
```

**Comment by caelinsutch** [comment]
Yup that was it, just me making dumb moves lol. Thanks for the help!
