### ISSUE TITLE
Cannot be used with Electron on Windows

### ISSUE THREAD

**Issue by adeelarshad83** [RobotWebTools/rclnodejs#839]
As the module working fine in nodejs app, I added the module in my actual requirement as I have to use in a desktop app made in electron js

I am facing following issue
App threw an error during load
Error: The module '\\?\D:\Projects\Embeddedesk\ad-base-station\app\node_modules\rclnodejs\build\Release\rclnodejs.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 101. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1800)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (D:\Projects\Embeddedesk\ad-base-station\app\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (D:\Projects\Embeddedesk\ad-base-station\app\node_modules\rclnodejs\lib\clock.js:17:38)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)

- Library Version: 0.21.0
- ROS Version: 2 (Foxy)
- Platform / OS: Windows 10
- Node Version: 16.14.0
- Electron Version: 17.0.0

**Expected Behavior**
Application should run seamlessly

**Actual Behavior**
Facing above issue on running of app

**Comment by minggangw** [comment]
Please reference https://github.com/RobotWebTools/rclnodejs/tree/develop/electron_demo, close this issue.
